import requests
import pandas as pd
from datetime import datetime, timedelta

API_KEY = "6206e4e96646c240ac59f09bc0164ff9"

start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 12, 31)

rows = []

current = start_date

while current <= end_date:

    target_dt = current.strftime("%Y%m%d")

    url = (
        "http://www.kobis.or.kr/kobisopenapi/webservice/rest/"
        f"boxoffice/searchDailyBoxOfficeList.json"
        f"?key={API_KEY}&targetDt={target_dt}"
    )

    result = requests.get(url).json()

    boxoffice = result['boxOfficeResult']['dailyBoxOfficeList']

    for movie in boxoffice:

        rows.append({
            '날짜': target_dt,
            '순위': movie['rank'],
            '영화명': movie['movieNm'],
            '개봉일': movie['openDt'],
            '일일관객수': movie['audiCnt'],
            '누적관객수': movie['audiAcc'],
            '일일매출액': movie['salesAmt']
        })

    current += timedelta(days=1)

df = pd.DataFrame(rows)

print(df.head())

In [14]:
df.shape

(3650, 7)

In [15]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      3650 non-null   object
 1   순위      3650 non-null   object
 2   영화명     3650 non-null   object
 3   개봉일     3650 non-null   object
 4   일일관객수   3650 non-null   object
 5   누적관객수   3650 non-null   object
 6   일일매출액   3650 non-null   object
dtypes: object(7)
memory usage: 199.7+ KB

         날짜 순위              영화명         개봉일   일일관객수    누적관객수       일일매출액
0  20250101  1              하얼빈  2024-12-24  340484  3095720  3290065760
1  20250101  2   보고타: 마지막 기회의 땅  2024-12-31   93154   194095   880276910
2  20250101  3              소방관  2024-12-04   80830  3398126   769063260
3  20250101  4           수퍼 소닉3  2025-01-01   75916    97373   705207940
4  20250101  5  뽀로로 극장판 바닷속 대모험  2025-01-01   58882    92837   512345060

- 월별 박스오피스 1등 리스트업

In [18]:
# df 객체를 파일로 저장
df.to_csv('data/kobis.csv', encoding='utf-8', index=False)

In [ ]:
df.dtypes

# '날짜' 컬럼의 데이터타입 변경 - datime
df['날짜'] = pd.to_datetime(df['날짜'])
df.dtypes

# 년, 월, 일, 요일 컬럼 생성
df['연도'] = df['날짜'].dt.year
df['월'] = df['날짜'].dt.month
df['일'] = df['날짜'].dt.day
df['요일'] = df['날짜'].dt.weekday
df

In [25]:
# 요일 변경
week_dict = {
     0: '월',
     1: '화',
     2: '수',
     3: '목',
     4: '금',
     5: '토',
     6: '일'
}
df['요일'] = df['날짜'].dt.weekday.map(week_dict)
df['요일'].value_counts()

요일
수    530
목    520
금    520
토    520
일    520
월    520
화    520
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      3650 non-null   datetime64[ns]
 1   순위      3650 non-null   object
 2   영화명     3650 non-null   object
 3   개봉일     3650 non-null   object
 4   일일관객수   3650 non-null   object
 5   누적관객수   3650 non-null   object
 6   일일매출액   3650 non-null   object
 7   연도      3650 non-null   int32
 8   월       3650 non-null   int32
 9   일       3650 non-null   int32
 10  요일      3650 non-null   object
dtypes: datetime64[ns](1), int32(3), object(7)
memory usage: 271.0+ KB

In [28]:
df

,날짜,순위,영화명,개봉일,일일관객수,누적관객수,일일매출액,연도,월,일,요일
0,2025-01-01,1,하얼빈,2024-12-24,340484,3095720,3290065760,2025,1,1,수
1,2025-01-01,2,보고타: 마지막 기회의 땅,2024-12-31,93154,194095,880276910,2025,1,1,수
2,2025-01-01,3,소방관,2024-12-04,80830,3398126,769063260,2025,1,1,수
3,2025-01-01,4,수퍼 소닉3,2025-01-01,75916,97373,705207940,2025,1,1,수
4,2025-01-01,5,뽀로로 극장판 바닷속 대모험,2025-01-01,58882,92837,512345060,2025,1,1,수
...,...,...,...,...,...,...,...,...,...,...,...
3645,2025-12-31,6,극장판 짱구는 못말려: 초화려! 작열하는 떡잎마을 댄서즈,2025-12-24,18979,327390,154747310,2025,12,31,수
3646,2025-12-31,7,화양연화 특별판,2025-12-31,9292,11279,80027452,2025,12,31,수
3647,2025-12-31,8,뽀로로 극장판 스위트캐슬 대모험,2025-12-11,4807,216003,41105520,2025,12,31,수
3648,2025-12-31,9,누벨바그,2025-12-31,4051,4597,24782960,2025,12,31,수
3649,2025-12-31,10,파더 마더 시스터 브라더,2025-12-31,3216,5344,26807400,2025,12,31,수

In [35]:
df['순위'].value_counts()
df_rank1 = df[df['순위'] == '1']
df_rank1

# 2025년 기준 Top of Top 10

,날짜,순위,영화명,개봉일,일일관객수,누적관객수,일일매출액,연도,월,일,요일
0,2025-01-01,1,하얼빈,2024-12-24,340484,3095720,3290065760,2025,1,1,수
10,2025-01-02,1,하얼빈,2024-12-24,92862,3188582,850528040,2025,1,2,목
20,2025-01-03,1,하얼빈,2024-12-24,91398,3279980,869700750,2025,1,3,금
30,2025-01-04,1,하얼빈,2024-12-24,218542,3498522,2140702910,2025,1,4,토
40,2025-01-05,1,하얼빈,2024-12-24,174400,3672922,1698746070,2025,1,5,일
...,...,...,...,...,...,...,...,...,...,...,...
3600,2025-12-27,1,아바타: 불과 재,2025-12-17,416651,3671395,4882594660,2025,12,27,토
3610,2025-12-28,1,아바타: 불과 재,2025-12-17,364963,4036358,4243646380,2025,12,28,일
3620,2025-12-29,1,아바타: 불과 재,2025-12-17,138756,4175114,1602159840,2025,12,29,월
3630,2025-12-30,1,아바타: 불과 재,2025-12-17,138613,4313727,1573424620,2025,12,30,화
3640,2025-12-31,1,아바타: 불과 재,2025-12-17,255811,4569538,2528548820,2025,12,31,수